version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
    data:
      driver: local
